/***************************************************************/
/* C-file generated by CC1200 Control Center                   */
/*                                                             */
/*  Generated at 4/14/2021  7:44.56                             */
/***************************************************************/
 
#define  IOCFG3             0x00 
#define  IOCFG2             0x01 
#define  IOCFG1             0x02 
#define  IOCFG0             0x03 
#define  SYNC3              0x04 
#define  SYNC2              0x05 
#define  SYNC1              0x06 
#define  SYNC0              0x07 
#define  SYNC_CFG1          0x08 
#define  SYNC_CFG0          0x09 
#define  DEVIATION_M        0x0A 
#define  MODCFG_DEV_E       0x0B 
#define  DCFILT_CFG         0x0C 
#define  PREAMBLE_CFG1      0X0D 
#define  PREAMBLE_CFG0      0x0E 
#define  IQIC               0x0F 
#define  CHAN_BW            0x10 
#define  MDMCFG1            0x11 
#define  MDMCFG0            0x12 
#define  SYMBOL_RATE2       0x13 
#define  SYMBOL_RATE1       0x14 
#define  SYMBOL_RATE0       0x15 
#define  AGC_REF            0x16 
#define  AGC_CS_THR         0x17 
#define  AGC_GAIN_ADJUST    0x18 
#define  AGC_CFG3           0x19 
#define  AGC_CFG2           0x1A 
#define  AGC_CFG1           0x1B 
#define  AGC_CFG0           0x1C 
#define  FIFO_CFG           0X1D 
#define  DEV_ADDR           0x1E 
#define  SETTLING_CFG       0x1F 
#define  FS_CFG             0x20 
#define  WOR_CFG1           0x21 
#define  WOR_CFG0           0x22 
#define  WOR_EVENT0_MSB     0x23 
#define  WOR_EVENT0_LSB     0x24 
#define  RXDCM_TIME         0x25 
#define  PKT_CFG2           0x26 
#define  PKT_CFG1           0x27 
#define  PKT_CFG0           0x28 
#define  RFEND_CFG1         0x29 
#define  RFEND_CFG0         0x2A 
#define  PA_CFG1            0x2B 
#define  PA_CFG0            0x2C 
#define  ASK_CFG            0X2D 
#define  PKT_LEN            0x2E 
#define  IF_MIX_CFG         0x2F00
#define  FREQOFF_CFG        0x2F01
#define  TOC_CFG            0x2F02
#define  MARC_SPARE         0x2F03
#define  ECG_CFG            0x2F04
#define  MDMCFG2            0x2F05
#define  EXT_CTRL           0x2F06
#define  RCCAL_FINE         0x2F07
#define  RCCAL_COARSE       0x2F08
#define  RCCAL_OFFSET       0x2F09
#define  FREQOFF1           0x2F0A
#define  FREQOFF0           0x2F0B
#define  FREQ2              0x2F0C
#define  FREQ1              0x2F0D
#define  FREQ0              0x2F0E
#define  IF_ADC2            0x2F0F
#define  IF_ADC1            0x2F10
#define  IF_ADC0            0x2F11
#define  FS_DIG1            0x2F12
#define  FS_DIG0            0x2F13
#define  FS_CAL3            0x2F14
#define  FS_CAL2            0x2F15
#define  FS_CAL1            0x2F16
#define  FS_CAL0            0x2F17
#define  FS_CHP             0x2F18
#define  FS_DIVTWO          0x2F19
#define  FS_DSM1            0x2F1A
#define  FS_DSM0            0x2F1B
#define  FS_DVC1            0x2F1C
#define  FS_DVC0            0x2F1D
#define  FS_LBI             0x2F1E
#define  FS_PFD             0x2F1F
#define  FS_PRE             0x2F20
#define  FS_REG_DIV_CML     0x2F21
#define  FS_SPARE           0x2F22
#define  FS_VCO4            0x2F23
#define  FS_VCO3            0x2F24
#define  FS_VCO2            0x2F25
#define  FS_VCO1            0x2F26
#define  FS_VCO0            0x2F27
#define  GBIAS6             0x2F28
#define  GBIAS5             0x2F29
#define  GBIAS4             0x2F2A
#define  GBIAS3             0x2F2B
#define  GBIAS2             0x2F2C
#define  GBIAS1             0x2F2D
#define  GBIAS0             0x2F2E
#define  IFAMP              0x2F2F
#define  LNA                0x2F30
#define  RXMIX              0x2F31
#define  XOSC5              0x2F32
#define  XOSC4              0x2F33
#define  XOSC3              0x2F34
#define  XOSC2              0x2F35
#define  XOSC1              0x2F36
#define  XOSC0              0x2F37
#define  ANALOG_SPARE       0x2F38
#define  PA_CFG3            0x2F39
#define  WOR_TIME1          0x2F64
#define  WOR_TIME0          0x2F65
#define  WOR_CAPTURE1       0x2F66
#define  WOR_CAPTURE0       0x2F67
#define  BIST               0x2F68
#define  DCFILTOFFSET_I1    0x2F69
#define  DCFILTOFFSET_I0    0x2F6A
#define  DCFILTOFFSET_Q1    0x2F6B
#define  DCFILTOFFSET_Q0    0x2F6C
#define  IQIE_I1            0x2F6D
#define  IQIE_I0            0x2F6E
#define  IQIE_Q1            0x2F6F
#define  IQIE_Q0            0x2F70
#define  RSSI1              0x2F71
#define  RSSI0              0x2F72
#define  MARCSTATE          0x2F73
#define  LQI_VAL            0x2F74
#define  PQT_SYNC_ERR       0x2F75
#define  DEM_STATUS         0x2F76
#define  FREQOFF_EST1       0x2F77
#define  FREQOFF_EST0       0x2F78
#define  AGC_GAIN3          0x2F79
#define  AGC_GAIN2          0x2F7A
#define  AGC_GAIN1          0x2F7B
#define  AGC_GAIN0          0x2F7C
#define  CFM_RX_DATA_OUT    0x2F7D
#define  CFM_TX_DATA_IN     0x2F7E
#define  ASK_SOFT_RX_DATA   0x2F7F
#define  RNDGEN             0x2F80
#define  MAGN2              0x2F81
#define  MAGN1              0x2F82
#define  MAGN0              0x2F83
#define  ANG1               0x2F84
#define  ANG0               0x2F85
#define  CHFILT_I2          0x2F86
#define  CHFILT_I1          0x2F87
#define  CHFILT_I0          0x2F88
#define  CHFILT_Q2          0x2F89
#define  CHFILT_Q1          0x2F8A
#define  CHFILT_Q0          0x2F8B
#define  GPIO_STATUS        0x2F8C
#define  FSCAL_CTRL         0x2F8D
#define  PHASE_ADJUST       0x2F8E
#define  PARTNUMBER         0x2F8F
#define  PARTVERSION        0x2F90
#define  SERIAL_STATUS      0x2F91
#define  MODEM_STATUS1      0x2F92
#define  MODEM_STATUS0      0x2F93
#define  MARC_STATUS1       0x2F94
#define  MARC_STATUS0       0x2F95
#define  PA_IFAMP_TEST      0x2F96
#define  FSRF_TEST          0x2F97
#define  PRE_TEST           0x2F98
#define  PRE_OVR            0x2F99
#define  ADC_TEST           0x2F9A
#define  DVC_TEST           0x2F9B
#define  ATEST              0x2F9C
#define  ATEST_LVDS         0x2F9D
#define  ATEST_MODE         0x2F9E
#define  XOSC_TEST1         0x2F9F
#define  XOSC_TEST0         0x2FA0
#define  AES                0x2FA1
#define  MDM_TEST           0x2FA2
#define  RXFIRST            0x2FD2
#define  TXFIRST            0x2FD3
#define  RXLAST             0x2FD4
#define  TXLAST             0x2FD5
#define  NUM_TXBYTES        0x2FD6
#define  NUM_RXBYTES        0x2FD7
#define  FIFO_NUM_TXBYTES   0x2FD8
#define  FIFO_NUM_RXBYTES   0x2FD9
#define  RXFIFO_PRE_BUF     0x2FDA

typedef struct {
        int adr;  /**< Register Adresse  */
        int val;  /**< Wert des Registers */
} REG_TYPE;

#define MAX_REG  47
#define MAX_EXT_REG  130

REG_TYPE RegSettings[MAX_REG] =
{
    {IOCFG3         , 0x06 }, // GPIO3 IO Pin Configuration
    {IOCFG2         , 0x08 }, // GPIO2 IO Pin Configuration
    {IOCFG1         , 0x30 }, // GPIO1 IO Pin Configuration
    {IOCFG0         , 0x09 }, // GPIO0 IO Pin Configuration
    {SYNC3          , 0x93 }, // Sync Word Configuration [31:24]
    {SYNC2          , 0x0b }, // Sync Word Configuration [23:16]
    {SYNC1          , 0x51 }, // Sync Word Configuration [15:8]
    {SYNC0          , 0xde }, // Sync Word Configuration [7:0]
    {SYNC_CFG1      , 0xbf }, // Sync Word Detection Configuration Reg. 1
    {SYNC_CFG0      , 0x03 }, // Sync Word Detection Configuration Reg. 0
    {DEVIATION_M    , 0x06 }, // Frequency Deviation Configuration
    {MODCFG_DEV_E   , 0x0b }, // Modulation Format and Frequency Deviation Configur..
    {DCFILT_CFG     , 0x4c }, // Digital DC Removal Configuration
    {PREAMBLE_CFG1  , 0x01 }, // Preamble Length Configuration Reg. 1 (reset);
    {PREAMBLE_CFG0  , 0x8a }, // Preamble Detection Configuration Reg. 0
    {IQIC           , 0xc8 }, // Digital Image Channel Compensation Configuration
    {CHAN_BW        , 0x10 }, // Channel Filter Configuration
    {MDMCFG1        , 0x02 }, // General Modem Parameter Configuration Reg. 1
    {MDMCFG0        , 0x05 }, // General Modem Parameter Configuration Reg. 0
    {SYMBOL_RATE2   , 0x8f }, // Symbol Rate Configuration Exponent and Mantissa [1..
    {SYMBOL_RATE1   , 0x75 }, // Symbol Rate Configuration Mantissa [15:8]
    {SYMBOL_RATE0   , 0x10 }, // Symbol Rate Configuration Mantissa [7:0]
    {AGC_REF        , 0x27 }, // AGC Reference Level Configuration
    {AGC_CS_THR     , 0xee }, // Carrier Sense Threshold Configuration
    {AGC_GAIN_ADJUST, 0x30 }, // RSSI Offset Configuration
    {AGC_CFG3       , 0x11 }, // Automatic Gain Control Configuration Reg. 3
    {AGC_CFG2       , 0x20 }, // Automatic Gain Control Configuration Reg. 2
    {AGC_CFG1       , 0x11 }, // Automatic Gain Control Configuration Reg. 1
    {AGC_CFG0       , 0x94 }, // Automatic Gain Control Configuration Reg. 0
    {FIFO_CFG       , 0x00 }, // FIFO Configuration
    {DEV_ADDR       , 0x00 }, // Device Address Configuration
    {SETTLING_CFG   , 0x0b }, // Frequency Synthesizer Calibration and Settling Con..
    {FS_CFG         , 0x12 }, // Frequency Synthesizer Configuration
    {WOR_CFG1       , 0x08 }, // eWOR Configuration Reg. 1
    {WOR_CFG0       , 0x21 }, // eWOR Configuration Reg. 0
    {WOR_EVENT0_MSB , 0x00 }, // Event 0 Configuration MSB
    {WOR_EVENT0_LSB , 0x00 }, // Event 0 Configuration LSB
    {RXDCM_TIME     , 0x00 }, // RX Duty Cycle Mode Configuration
    {PKT_CFG2       , 0x01 }, // Packet Configuration Reg. 2 (on reset)
    {PKT_CFG1       , 0x00 }, // Packet Configuration Reg. 1 (on reset)
    {PKT_CFG0       , 0x20 }, // Packet Configuration Reg. 0 (on reset)
    {RFEND_CFG1     , 0x0f }, // RFEND Configuration Reg. 1
    {RFEND_CFG0     , 0x00 }, // RFEND Configuration Reg. 0
    {PA_CFG1        , 0x7f }, // Power Amplifier Configuration Reg. 1
    {PA_CFG0        , 0x56 }, // Power Amplifier Configuration Reg. 0
    {ASK_CFG        , 0x0f }, // ASK Configuration
    {PKT_LEN        , 0xff }  // Packet Length Configuration
};

REG_TYPE ExtRegSettings[MAX_EXT_REG] =
{
    {IF_MIX_CFG      , 0x1c },  // IF Mix Configuration
    {FREQOFF_CFG     , 0x22 },  // Frequency Offset Correction Configuration (on Reset)
    {TOC_CFG         , 0x03 },  // Timing Offset Correction Configuration (reset value)
    {MARC_SPARE      , 0x00 },  // MARC Spare
    {ECG_CFG         , 0x00 },  // External Clock Frequency Configuration
    {MDMCFG2         , 0x02 },  // General Modem Parameter Configuration Reg. 2
    {EXT_CTRL        , 0x01 },  // External Control Configuration
    {RCCAL_FINE      , 0x00 },  // RC Oscillator Calibration Fine
    {RCCAL_COARSE    , 0x00 },  // RC Oscillator Calibration Coarse
    {RCCAL_OFFSET    , 0x00 },  // RC Oscillator Calibration Clock Offset
    {FREQOFF1        , 0x00 },  // Frequency Offset MSB
    {FREQOFF0        , 0x00 },  // Frequency Offset LSB
    {FREQ2           , 0x56 },  // Frequency Configuration [23:16]
    {FREQ1           , 0xcc },  // Frequency Configuration [15:8]
    {FREQ0           , 0xcc },  // Frequency Configuration [7:0]
    {IF_ADC2         , 0x02 },  // Analog to Digital Converter Configuration Reg. 2
    {IF_ADC1         , 0xee },  // Analog to Digital Converter Configuration Reg. 1
    {IF_ADC0         , 0x10 },  // Analog to Digital Converter Configuration Reg. 0
    {FS_DIG1         , 0x07 },  // Frequency Synthesizer Digital Reg. 1
    {FS_DIG0         , 0xaf },  // Frequency Synthesizer Digital Reg. 0
    {FS_CAL3         , 0x00 },  // Frequency Synthesizer Calibration Reg. 3
    {FS_CAL2         , 0x20 },  // Frequency Synthesizer Calibration Reg. 2
    {FS_CAL1         , 0x40 },  // Frequency Synthesizer Calibration Reg. 1
    {FS_CAL0         , 0x0e },  // Frequency Synthesizer Calibration Reg. 0
    {FS_CHP          , 0x2b },  // Frequency Synthesizer Charge Pump Configuration
    {FS_DIVTWO       , 0x03 },  // Frequency Synthesizer Divide by 2
    {FS_DSM1         , 0x00 },  // FS Digital Synthesizer Module Configuration Reg. 1
    {FS_DSM0         , 0x33 },  // FS Digital Synthesizer Module Configuration Reg. 0
    {FS_DVC1         , 0xff },  // Frequency Synthesizer Divider Chain Configuration ..
    {FS_DVC0         , 0x17 },  // Frequency Synthesizer Divider Chain Configuration ..
    {FS_LBI          , 0x00 },  // Frequency Synthesizer Local Bias Configuration
    {FS_PFD          , 0x00 },  // Frequency Synthesizer Phase Frequency Detector Con..
    {FS_PRE          , 0x6e },  // Frequency Synthesizer Prescaler Configuration
    {FS_REG_DIV_CML  , 0x1c },  // Frequency Synthesizer Divider Regulator Configurat..
    {FS_SPARE        , 0xac },  // Frequency Synthesizer Spare
    {FS_VCO4         , 0x13 },  // FS Voltage Controlled Oscillator Configuration Reg..
    {FS_VCO3         , 0x00 },  // FS Voltage Controlled Oscillator Configuration Reg..
    {FS_VCO2         , 0x4a },  // FS Voltage Controlled Oscillator Configuration Reg..
    {FS_VCO1         , 0xac },  // FS Voltage Controlled Oscillator Configuration Reg..
    {FS_VCO0         , 0xb5 },  // FS Voltage Controlled Oscillator Configuration Reg..
    {GBIAS6          , 0x00 },  // Global Bias Configuration Reg. 6
    {GBIAS5          , 0x02 },  // Global Bias Configuration Reg. 5
    {GBIAS4          , 0x00 },  // Global Bias Configuration Reg. 4
    {GBIAS3          , 0x00 },  // Global Bias Configuration Reg. 3
    {GBIAS2          , 0x10 },  // Global Bias Configuration Reg. 2
    {GBIAS1          , 0x00 },  // Global Bias Configuration Reg. 1
    {GBIAS0          , 0x00 },  // Global Bias Configuration Reg. 0
    {IFAMP           , 0x09 },  // Intermediate Frequency Amplifier Configuration
    {LNA             , 0x01 },  // Low Noise Amplifier Configuration
    {RXMIX           , 0x01 },  // RX Mixer Configuration
    {XOSC5           , 0x0e },  // Crystal Oscillator Configuration Reg. 5
    {XOSC4           , 0xa0 },  // Crystal Oscillator Configuration Reg. 4
    {XOSC3           , 0x03 },  // Crystal Oscillator Configuration Reg. 3
    {XOSC2           , 0x04 },  // Crystal Oscillator Configuration Reg. 2
    {XOSC1           , 0x03 },  // Crystal Oscillator Configuration Reg. 1
    {XOSC0           , 0x00 },  // Crystal Oscillator Configuration Reg. 0
    {ANALOG_SPARE    , 0x00 },  // Analog Spare
    {PA_CFG3         , 0x00 },  // Power Amplifier Configuration Reg. 3
    {WOR_TIME1       , 0x00 },  // eWOR Timer Counter Value MSB
    {WOR_TIME0       , 0x00 },  // eWOR Timer Counter Value LSB
    {WOR_CAPTURE1    , 0x00 },  // eWOR Timer Capture Value MSB
    {WOR_CAPTURE0    , 0x00 },  // eWOR Timer Capture Value LSB
    {BIST            , 0x00 },  // MARC Built-In Self-Test
    {DCFILTOFFSET_I1 , 0x00 },  // DC Filter Offset I MSB
    {DCFILTOFFSET_I0 , 0x00 },  // DC Filter Offset I LSB
    {DCFILTOFFSET_Q1 , 0x00 },  // DC Filter Offset Q MSB
    {DCFILTOFFSET_Q0 , 0x00 },  // DC Filter Offset Q LSB
    {IQIE_I1         , 0x00 },  // IQ Imbalance Value I MSB
    {IQIE_I0         , 0x40 },  // IQ Imbalance Value I LSB
    {IQIE_Q1         , 0x01 },  // IQ Imbalance Value Q MSB
    {IQIE_Q0         , 0x87 },  // IQ Imbalance Value Q LSB
    {RSSI1           , 0x13 },  // Received Signal Strength Indicator Reg. 1
    {RSSI0           , 0x47 },  // Received Signal Strength Indicator Reg.0
    {MARCSTATE       , 0x41 },  // MARC State
    {LQI_VAL         , 0x13 },  // Link Quality Indicator Value
    {PQT_SYNC_ERR    , 0xf9 },  // Preamble and Sync Word Error
    {DEM_STATUS      , 0x1a },  // Demodulator Status
    {FREQOFF_EST1    , 0x00 },  // Frequency Offset Estimate MSB
    {FREQOFF_EST0    , 0xf6 },  // Frequency Offset Estimate LSB
    {AGC_GAIN3       , 0x27 },  // Automatic Gain Control Reg. 3
    {AGC_GAIN2       , 0xd1 },  // Automatic Gain Control Reg. 2
    {AGC_GAIN1       , 0x00 },  // Automatic Gain Control Reg. 1
    {AGC_GAIN0       , 0x3f },  // Automatic Gain Control Reg. 0
    {CFM_RX_DATA_OUT , 0x00 },  // Custom Frequency Modulation RX Data
    {CFM_TX_DATA_IN  , 0x00 },  // Custom Frequency Modulation TX Data
    {ASK_SOFT_RX_DATA, 0x30 },  //:ASK Soft Decision Output
    {RNDGEN          , 0x7f },  // Random Number Generator Value
    {MAGN2           , 0x00 },  // Signal Magnitude after CORDIC [16]
    {MAGN1           , 0x00 },  // Signal Magnitude after CORDIC [15:8]
    {MAGN0           , 0x0e },  // Signal Magnitude after CORDIC [7:0]
    {ANG1            , 0x01 },  // Signal Angular after CORDIC [9:8]
    {ANG0            , 0x34 },  // Signal Angular after CORDIC [7:0]
    {CHFILT_I2       , 0x02 },  // Channel Filter Data Real Part [16]
    {CHFILT_I1       , 0x00 },  // Channel Filter Data Real Part [15:8]
    {CHFILT_I0       , 0x00 },  // Channel Filter Data Real Part [7:0]
    {CHFILT_Q2       , 0x00 },  // Channel Filter Data Imaginary Part [16]
    {CHFILT_Q1       , 0x00 },  // Channel Filter Data Imaginary Part [15:8]
    {CHFILT_Q0       , 0x00 },  // Channel Filter Data Imaginary Part [7:0]
    {GPIO_STATUS     , 0x0d },  // General Purpose Input/Output Status
    {FSCAL_CTRL      , 0x01 },  // Frequency Synthesizer Calibration Control
    {PHASE_ADJUST    , 0x00 },  // Frequency Synthesizer Phase Adjust
    {PARTNUMBER      , 0x20 },  // Part Number
    {PARTVERSION     , 0x11 },  // Part Revision
    {SERIAL_STATUS   , 0x08 },  // Serial Status
    {MODEM_STATUS1   , 0x91 },  // Modem Status Reg. 1
    {MODEM_STATUS0   , 0x00 },  // Modem Status Reg. 0
    {MARC_STATUS1    , 0x00 },  // MARC Status Reg. 1
    {MARC_STATUS0    , 0x00 },  // MARC Status Reg. 0
    {PA_IFAMP_TEST   , 0x00 },  // Power Amplifier Intermediate Frequency Amplifier T..
    {FSRF_TEST       , 0x00 },  // Frequency Synthesizer Test
    {PRE_TEST        , 0x00 },  // Frequency Synthesizer Prescaler Test
    {PRE_OVR         , 0x00 },  // Frequency Synthesizer Prescaler Override
    {ADC_TEST        , 0x00 },  // Analog to Digital Converter Test
    {DVC_TEST        , 0x0b },  // Digital Divider Chain Test
    {ATEST           , 0x40 },  // Analog Test
    {ATEST_LVDS      , 0x00 },  // Analog Test LVDS
    {ATEST_MODE      , 0x00 },  // Analog Test Mode
    {XOSC_TEST1      , 0x3c },  // Crystal Oscillator Test Reg. 1
    {XOSC_TEST0      , 0x00 },  // Crystal Oscillator Test Reg. 0
    {AES             , 0x00 },  // AES
    {MDM_TEST        , 0x00 },  // MODEM Test
    {RXFIRST         , 0x00 },  // RX FIFO Pointer First Entry
    {TXFIRST         , 0x00 },  // TX FIFO Pointer First Entry
    {RXLAST          , 0x00 },  // RX FIFO Pointer Last Entry
    {TXLAST          , 0x00 },  // TX FIFO Pointer Last Entry
    {NUM_TXBYTES     , 0x00 },  // TX FIFO Status
    {NUM_RXBYTES     , 0x00 },  // RX FIFO Status
    {FIFO_NUM_TXBYTES, 0x0f },  //:TX FIFO Status
    {FIFO_NUM_RXBYTES, 0x00 },  //:RX FIFO Status
    {RXFIFO_PRE_BUF  , 0x00 }  // RX FIFO Status
};
